package com.nuoplus.system.model;

public class RolePermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.role_id
     *
     * @mbg.generated Tue May 16 10:38:59 CST 2017
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.resource_id
     *
     * @mbg.generated Tue May 16 10:38:59 CST 2017
     */
    private Long resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.permission
     *
     * @mbg.generated Tue May 16 10:38:59 CST 2017
     */
    private String permission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.role_id
     *
     * @return the value of role_permission.role_id
     *
     * @mbg.generated Tue May 16 10:38:59 CST 2017
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.role_id
     *
     * @param roleId the value for role_permission.role_id
     *
     * @mbg.generated Tue May 16 10:38:59 CST 2017
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.resource_id
     *
     * @return the value of role_permission.resource_id
     *
     * @mbg.generated Tue May 16 10:38:59 CST 2017
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.resource_id
     *
     * @param resourceId the value for role_permission.resource_id
     *
     * @mbg.generated Tue May 16 10:38:59 CST 2017
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.permission
     *
     * @return the value of role_permission.permission
     *
     * @mbg.generated Tue May 16 10:38:59 CST 2017
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.permission
     *
     * @param permission the value for role_permission.permission
     *
     * @mbg.generated Tue May 16 10:38:59 CST 2017
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }
}