package com.nuoplus.system.model;

import java.util.Date;

public class SysUserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.id
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.stu_bc_id
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Long stuBcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.realname
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.userType
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Integer usertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.birthday
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.nation
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.sex
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.no
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.major
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Long major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.classes
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Long classes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.department
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Long department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.identityCard
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private String identitycard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.graduateStatus
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Boolean graduatestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.hktype
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Boolean hktype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.level
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.years
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private String years;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.politicsStatus
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Byte politicsstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.phone1
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private String phone1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.phone2
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private String phone2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.matriculationTime
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Date matriculationtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.nativePlace
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private String nativeplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.birthplace
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private String birthplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.admissiono
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Boolean admissiono;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.admissionFiles
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Byte admissionfiles;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.admissionLetter
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Byte admissionletter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.entranceRegistration
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Byte entranceregistration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.memberProfile
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Byte memberprofile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.reportCard
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Byte reportcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.graduateRegistration
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Byte graduateregistration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.bachelorApplication
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Byte bachelorapplication;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.rewardsPunishment
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Byte rewardspunishment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.fullMembershipFiles
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Byte fullmembershipfiles;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.GraduatesCheckup
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Byte graduatescheckup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.certificateRegistry
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Byte certificateregistry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.noReportCard
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    private Byte noreportcard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.id
     *
     * @return the value of sys_user_info.id
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.id
     *
     * @param id the value for sys_user_info.id
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.stu_bc_id
     *
     * @return the value of sys_user_info.stu_bc_id
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Long getStuBcId() {
        return stuBcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.stu_bc_id
     *
     * @param stuBcId the value for sys_user_info.stu_bc_id
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setStuBcId(Long stuBcId) {
        this.stuBcId = stuBcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.realname
     *
     * @return the value of sys_user_info.realname
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.realname
     *
     * @param realname the value for sys_user_info.realname
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.userType
     *
     * @return the value of sys_user_info.userType
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Integer getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.userType
     *
     * @param usertype the value for sys_user_info.userType
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.birthday
     *
     * @return the value of sys_user_info.birthday
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.birthday
     *
     * @param birthday the value for sys_user_info.birthday
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.nation
     *
     * @return the value of sys_user_info.nation
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.nation
     *
     * @param nation the value for sys_user_info.nation
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.sex
     *
     * @return the value of sys_user_info.sex
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.sex
     *
     * @param sex the value for sys_user_info.sex
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.no
     *
     * @return the value of sys_user_info.no
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.no
     *
     * @param no the value for sys_user_info.no
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.major
     *
     * @return the value of sys_user_info.major
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Long getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.major
     *
     * @param major the value for sys_user_info.major
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setMajor(Long major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.classes
     *
     * @return the value of sys_user_info.classes
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Long getClasses() {
        return classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.classes
     *
     * @param classes the value for sys_user_info.classes
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setClasses(Long classes) {
        this.classes = classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.department
     *
     * @return the value of sys_user_info.department
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Long getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.department
     *
     * @param department the value for sys_user_info.department
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setDepartment(Long department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.identityCard
     *
     * @return the value of sys_user_info.identityCard
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public String getIdentitycard() {
        return identitycard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.identityCard
     *
     * @param identitycard the value for sys_user_info.identityCard
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setIdentitycard(String identitycard) {
        this.identitycard = identitycard == null ? null : identitycard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.graduateStatus
     *
     * @return the value of sys_user_info.graduateStatus
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Boolean getGraduatestatus() {
        return graduatestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.graduateStatus
     *
     * @param graduatestatus the value for sys_user_info.graduateStatus
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setGraduatestatus(Boolean graduatestatus) {
        this.graduatestatus = graduatestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.hktype
     *
     * @return the value of sys_user_info.hktype
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Boolean getHktype() {
        return hktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.hktype
     *
     * @param hktype the value for sys_user_info.hktype
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setHktype(Boolean hktype) {
        this.hktype = hktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.level
     *
     * @return the value of sys_user_info.level
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.level
     *
     * @param level the value for sys_user_info.level
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.years
     *
     * @return the value of sys_user_info.years
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public String getYears() {
        return years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.years
     *
     * @param years the value for sys_user_info.years
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setYears(String years) {
        this.years = years == null ? null : years.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.politicsStatus
     *
     * @return the value of sys_user_info.politicsStatus
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Byte getPoliticsstatus() {
        return politicsstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.politicsStatus
     *
     * @param politicsstatus the value for sys_user_info.politicsStatus
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setPoliticsstatus(Byte politicsstatus) {
        this.politicsstatus = politicsstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.phone1
     *
     * @return the value of sys_user_info.phone1
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public String getPhone1() {
        return phone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.phone1
     *
     * @param phone1 the value for sys_user_info.phone1
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setPhone1(String phone1) {
        this.phone1 = phone1 == null ? null : phone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.phone2
     *
     * @return the value of sys_user_info.phone2
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public String getPhone2() {
        return phone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.phone2
     *
     * @param phone2 the value for sys_user_info.phone2
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setPhone2(String phone2) {
        this.phone2 = phone2 == null ? null : phone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.matriculationTime
     *
     * @return the value of sys_user_info.matriculationTime
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Date getMatriculationtime() {
        return matriculationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.matriculationTime
     *
     * @param matriculationtime the value for sys_user_info.matriculationTime
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setMatriculationtime(Date matriculationtime) {
        this.matriculationtime = matriculationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.nativePlace
     *
     * @return the value of sys_user_info.nativePlace
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public String getNativeplace() {
        return nativeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.nativePlace
     *
     * @param nativeplace the value for sys_user_info.nativePlace
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setNativeplace(String nativeplace) {
        this.nativeplace = nativeplace == null ? null : nativeplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.birthplace
     *
     * @return the value of sys_user_info.birthplace
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public String getBirthplace() {
        return birthplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.birthplace
     *
     * @param birthplace the value for sys_user_info.birthplace
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setBirthplace(String birthplace) {
        this.birthplace = birthplace == null ? null : birthplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.admissiono
     *
     * @return the value of sys_user_info.admissiono
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Boolean getAdmissiono() {
        return admissiono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.admissiono
     *
     * @param admissiono the value for sys_user_info.admissiono
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setAdmissiono(Boolean admissiono) {
        this.admissiono = admissiono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.admissionFiles
     *
     * @return the value of sys_user_info.admissionFiles
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Byte getAdmissionfiles() {
        return admissionfiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.admissionFiles
     *
     * @param admissionfiles the value for sys_user_info.admissionFiles
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setAdmissionfiles(Byte admissionfiles) {
        this.admissionfiles = admissionfiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.admissionLetter
     *
     * @return the value of sys_user_info.admissionLetter
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Byte getAdmissionletter() {
        return admissionletter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.admissionLetter
     *
     * @param admissionletter the value for sys_user_info.admissionLetter
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setAdmissionletter(Byte admissionletter) {
        this.admissionletter = admissionletter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.entranceRegistration
     *
     * @return the value of sys_user_info.entranceRegistration
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Byte getEntranceregistration() {
        return entranceregistration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.entranceRegistration
     *
     * @param entranceregistration the value for sys_user_info.entranceRegistration
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setEntranceregistration(Byte entranceregistration) {
        this.entranceregistration = entranceregistration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.memberProfile
     *
     * @return the value of sys_user_info.memberProfile
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Byte getMemberprofile() {
        return memberprofile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.memberProfile
     *
     * @param memberprofile the value for sys_user_info.memberProfile
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setMemberprofile(Byte memberprofile) {
        this.memberprofile = memberprofile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.reportCard
     *
     * @return the value of sys_user_info.reportCard
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Byte getReportcard() {
        return reportcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.reportCard
     *
     * @param reportcard the value for sys_user_info.reportCard
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setReportcard(Byte reportcard) {
        this.reportcard = reportcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.graduateRegistration
     *
     * @return the value of sys_user_info.graduateRegistration
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Byte getGraduateregistration() {
        return graduateregistration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.graduateRegistration
     *
     * @param graduateregistration the value for sys_user_info.graduateRegistration
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setGraduateregistration(Byte graduateregistration) {
        this.graduateregistration = graduateregistration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.bachelorApplication
     *
     * @return the value of sys_user_info.bachelorApplication
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Byte getBachelorapplication() {
        return bachelorapplication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.bachelorApplication
     *
     * @param bachelorapplication the value for sys_user_info.bachelorApplication
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setBachelorapplication(Byte bachelorapplication) {
        this.bachelorapplication = bachelorapplication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.rewardsPunishment
     *
     * @return the value of sys_user_info.rewardsPunishment
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Byte getRewardspunishment() {
        return rewardspunishment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.rewardsPunishment
     *
     * @param rewardspunishment the value for sys_user_info.rewardsPunishment
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setRewardspunishment(Byte rewardspunishment) {
        this.rewardspunishment = rewardspunishment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.fullMembershipFiles
     *
     * @return the value of sys_user_info.fullMembershipFiles
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Byte getFullmembershipfiles() {
        return fullmembershipfiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.fullMembershipFiles
     *
     * @param fullmembershipfiles the value for sys_user_info.fullMembershipFiles
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setFullmembershipfiles(Byte fullmembershipfiles) {
        this.fullmembershipfiles = fullmembershipfiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.GraduatesCheckup
     *
     * @return the value of sys_user_info.GraduatesCheckup
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Byte getGraduatescheckup() {
        return graduatescheckup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.GraduatesCheckup
     *
     * @param graduatescheckup the value for sys_user_info.GraduatesCheckup
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setGraduatescheckup(Byte graduatescheckup) {
        this.graduatescheckup = graduatescheckup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.certificateRegistry
     *
     * @return the value of sys_user_info.certificateRegistry
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Byte getCertificateregistry() {
        return certificateregistry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.certificateRegistry
     *
     * @param certificateregistry the value for sys_user_info.certificateRegistry
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setCertificateregistry(Byte certificateregistry) {
        this.certificateregistry = certificateregistry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.noReportCard
     *
     * @return the value of sys_user_info.noReportCard
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public Byte getNoreportcard() {
        return noreportcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.noReportCard
     *
     * @param noreportcard the value for sys_user_info.noReportCard
     *
     * @mbg.generated Fri Jun 23 13:54:45 CST 2017
     */
    public void setNoreportcard(Byte noreportcard) {
        this.noreportcard = noreportcard;
    }
}