package com.nuoplus.system.model;

public class SysUserRoles {
    public SysUserRoles(Long userId, Long roleId) {
        this.userId = userId;
        this.roleId = roleId;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_roles.user_id
     *
     * @mbg.generated Thu May 11 18:57:59 CST 2017
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_roles.role_id
     *
     * @mbg.generated Thu May 11 18:57:59 CST 2017
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_roles.sort
     *
     * @mbg.generated Thu May 11 18:57:59 CST 2017
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_roles.user_id
     *
     * @return the value of sys_user_roles.user_id
     *
     * @mbg.generated Thu May 11 18:57:59 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_roles.user_id
     *
     * @param userId the value for sys_user_roles.user_id
     *
     * @mbg.generated Thu May 11 18:57:59 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_roles.role_id
     *
     * @return the value of sys_user_roles.role_id
     *
     * @mbg.generated Thu May 11 18:57:59 CST 2017
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_roles.role_id
     *
     * @param roleId the value for sys_user_roles.role_id
     *
     * @mbg.generated Thu May 11 18:57:59 CST 2017
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_roles.sort
     *
     * @return the value of sys_user_roles.sort
     *
     * @mbg.generated Thu May 11 18:57:59 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_roles.sort
     *
     * @param sort the value for sys_user_roles.sort
     *
     * @mbg.generated Thu May 11 18:57:59 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}