package com.nuoplus.system.dao;

import com.nuoplus.system.model.SysDictionary;

import java.util.List;
import java.util.Map;

public interface SysDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbg.generated Thu May 25 17:51:30 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbg.generated Thu May 25 17:51:30 CST 2017
     */
    int insert(SysDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbg.generated Thu May 25 17:51:30 CST 2017
     */
    int insertSelective(SysDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbg.generated Thu May 25 17:51:30 CST 2017
     */
    SysDictionary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbg.generated Thu May 25 17:51:30 CST 2017
     */
    int updateByPrimaryKeySelective(SysDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbg.generated Thu May 25 17:51:30 CST 2017
     */
    int updateByPrimaryKey(SysDictionary record);

    /**
     * 查找全部词条
     * @return
     */

    List<SysDictionary> findAll();

    Integer countSubOrgByDicId(Map<String, Object> map);

    List<SysDictionary> findSubOrgByDicId(Map<String, Object> map);

    List<SysDictionary> findByparents(String checkbox);

    int batchDel(String checkbox);

    List<SysDictionary> findSubOrgByUid( Map<String, Object> map);

    //根据数据字典树父节点获取组织机构数子节点
    List<Map<String,Object>> getDicZtreeSubNodes(Long id);
}