package com.nuoplus.system.dao;

import com.nuoplus.system.model.SysOrganization;

import java.util.List;
import java.util.Map;

public interface SysOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated Wed May 03 11:03:47 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated Wed May 03 11:03:47 CST 2017
     */
    int insert(SysOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated Wed May 03 11:03:47 CST 2017
     */
    int insertSelective(SysOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated Wed May 03 11:03:47 CST 2017
     */
    SysOrganization selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated Wed May 03 11:03:47 CST 2017
     */
    int updateByPrimaryKeySelective(SysOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated Wed May 03 11:03:47 CST 2017
     */
    int updateByPrimaryKey(SysOrganization record);

    List<SysOrganization> findAll();

    List<SysOrganization> findAllWithExclude(Long orgId, String orgIds);

    List<SysOrganization> findOrganizationByUser(Long id);

    Integer countSubOrgByOrgId(Map<String, Object> id);

    List<SysOrganization> findSubOrgByOrgId(Map<String, Object> map);

    int batchDel(String checkbox);

    List<SysOrganization> findByparent(Long id);

    List<SysOrganization> findByparents(String ids);

    List<Map<String,Object>> getOrgZtreeSubNodes(Long id);
}