package com.nuoplus.system.dao;

import com.nuoplus.system.model.SysResource;

import java.util.List;
import java.util.Map;

public interface SysResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *1
     * @mbg.generated Wed May 03 11:03:47 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated Wed May 03 11:03:47 CST 2017
     */
    int insert(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated Wed May 03 11:03:47 CST 2017
     */
    int insertSelective(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated Wed May 03 11:03:47 CST 2017
     */
    SysResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated Wed May 03 11:03:47 CST 2017
     */
    int updateByPrimaryKeySelective(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated Wed May 03 11:03:47 CST 2017
     */
    int updateByPrimaryKey(SysResource record);

    List<SysResource> findAll();

    List<SysResource> findResourceNames(String resourceIds);

    List<SysResource> findResourceByUser(Long id);

    List<SysResource>  findSubMenuByResourceId(Map<String, Object> map);

    Integer countSubMenuByResourceId(Map<String, Object> id);

    int batchDel(String checkbox);

    List<SysResource> findByparent(Map<String, Object> id);

    List<SysResource> findByparents(String checkbox);

    List<SysResource> findMenusByUserId(Long userId);

    List<Map<String,Object>> getZtreeSubNodes(Long id);
}