package com.nuoplus.system.dao;

import com.nuoplus.system.model.SysRole;

import java.util.List;
import java.util.Map;

public interface SysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed May 03 11:03:47 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed May 03 11:03:47 CST 2017
     */
    int insert(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed May 03 11:03:47 CST 2017
     */
    int insertSelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed May 03 11:03:47 CST 2017
     */
    SysRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed May 03 11:03:47 CST 2017
     */
    int updateByPrimaryKeySelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This1 method corresponds to the database table sys_role
     *
     * @mbg.generated Wed May 03 11:03:47 CST 2017
     */
    int updateByPrimaryKey(SysRole record);

    SysRole findOne(Long roleId);

    List<SysRole> findAll();

    List<SysRole> findRoleNames(String roleIds);

    List<SysRole> findRolesByUser(Long id);

    Integer countAll(Map<String, Object> map);

    List<SysRole> findAllByPage(Map<String, Object> map);

    int batchDel(String checkbox);
}