package com.nuoplus.system.dao;

import com.nuoplus.system.model.SysUserOrganization;

import java.util.List;
import java.util.Map;

public interface SysUserOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_resource
     *
     * @mbg.generated Thu May 11 15:13:44 CST 2017
     */
    int deleteByPrimaryKey(SysUserOrganization key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_resource
     *
     * @mbg.generated Thu May 11 15:13:44 CST 2017
     */
    int insert(SysUserOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_resource
     *
     * @mbg.generated Thu May 11 15:13:44 CST 2017
     */
    int insertSelective(SysUserOrganization record);

    int deleteByUserId(Long id);

    List<Map<String,Object>> findOrgInfoByUsername(String username);

    List<Map<String,Object>> findParentOrgInfoByUsername(String username);
}