package com.nuoplus.system.dao;

import com.nuoplus.system.model.SysUserRoles;

import java.util.List;

public interface SysUserRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_roles
     *
     * @mbg.generated Thu May 11 18:57:59 CST 2017
     */
    int deleteByPrimaryKey(SysUserRoles key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_roles
     *
     * @mbg.generated Thu May 11 18:57:59 CST 2017
     */
    int insert(SysUserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_roles
     *
     * @mbg.generated Thu May 11 18:57:59 CST 2017
     */
    int insertSelective(SysUserRoles record);

    int deleteRolesByUser(Long id);

    List<SysUserRoles> findByUser(Long userId);
}